### ISSUE TITLE
Add Functions for Line Broadening and Supression because of Survey Resolution

### ISSUE THREAD

**Issue by Sefa76** [Sefa76/SSLimPy#1]
https://github.com/Sefa76/SSLimPy/blob/67b935d6117ae8b0bea9bb47435758c42ef84785/SSLimPy/LIMsurvey/PowerSpectra.py#L310

**Comment by Sefa76** [comment]
Hello @jl-bernal ,
I wanted to unravel a bit of what this issue is about and do kind of a task list. For the sake of clarity I have linked a new branch just for this task. Also there are some open points to discuss.

The necessary tasks for the line broadening are:
- [x] Identify in which file we want to compute the necessary quantity
- [x] read function to compute v(M). The [Chung paper](https://arxiv.org/pdf/2104.11171) argues that the exact shape has small impact, so we could most likely handle it in the astro_dict (?)
- [x] compute sigma_v(M)
- [x] inside of astro : add this to L_moments and to bavg
- [x] everywhere else use the force reshape to fix the errors in the k-dim index

The suppression due to resolution was previously handled in line_obs. I think we might also just be able to outsource this. 
For the suppression we have to do:
- [x] read dnu and Theta_FWHM from the survey specifications
- [x] compute inside of Power Spectra the resolution window function
- [x] Multiply PS with the window functions to add suppression 
This should also multiply the shot noise terms if I understand correctly as in real space we would convolve with the halo shape and with the resolution. This is also what is found in the paper. But I still have a hard time getting an intuition for this as its like that we are "suppressing  noise". The shot noise term shows up when computing the expectation value when two points would correspond to the same halo so why does the survey resolution matter?

Finally we also need to add the convolution with the survey volume
We can stay pretty close to the excising lim implementation.
I wanted to add them to the (still barren) covariance file as we will use the windows also for the SSC. So for completeness' sake:
- [x] Read Omega_field and Delta_nu from the survey specifications
- [x] Calculate L_field and S_field
- [x] Construct the survey window and convolve with the Power spectrum

**Comment by jl-bernal** [comment]
Hi @Sefa76, thanks for taking care of this and open the thread. 

Some comments regarding the tasks
- I don't think you need to implement this in the L_moments, since it effectively appears as another factor of (mass-dependent) RSD-like along the line of sight multiplication for clustering and shot noise. 
- Yeah, the shot noise must also be multiplied by the resolution windows. Note that shot noise is not actually "noise" (or at least "detector noise"). In the galaxy survey literature, it's treated as noise because it doesn't depend on cosmology, but it's a feature of the measurement. For LIM, it does depend on L^2(M), so it has some information (even if hard to interpret). Now, consider an unclustered population of galaxies emitting a spectral line: the power spectrum you measure is shot noise only. However, if there's resolution limit, that means that effectively you're applying a filter (i.e., blurring) your map, homogenizing everything on scales below the e.g., beam. That means that there's no clustering at all in scales below the beam (as they are homogenized), hence suppressing also the shot noise
- Not sure what you mean by outsourcing the resolution-limit suppression: are you planning to move that to Power Spectra too? 
- Regarding window function, so far we're assuming cylindrical volumes, we may want to leave open the possibility to consider other window functions (for the future, not to implement now)

**Comment by Sefa76** [comment]
Hello @jl-bernal,
Thank you for the reply and the explanation.
Regarding your first point: The reason why I wanted to have it in L-moments, is that that function enters in the RSD term and in the shotnoise term. I compared to the old lim code and found that this is similar to how the old function `Pshot `and `L2mean`, or `Pk_twohalo` and `Tmean`  did handle the `v_of_M` 

Thank you for helping me with my shot noise confusion again. I also thought about an interesting Gedankenexperiment: Lets say the shot noise (be it the one-halo or some additional shot noise) was not multiplied by the suppression. That would mean that for two experiments one with a very good resolution and one with a bad resolution both would measure the same small scale power spectrum. As the measured power spectrum of the bad-resolution experiment would be much more suppressed it would actually be better in measuring the shot noise as it sees the effect on a wider range of scales (whatever that means)

The outsourcing part was poorly explained by me sorry: If I wanted to follow my design strategy and separate the effects of for example Cosmology and Astrophysics one could argue that the detector/ survey effects should also be separate as they do not really depend on that. So yeah it is just a question of tidiness where I want to put that. And if you would be even more pedantic the same question arises for the sky selection window functions.       
 
 I hope this explains a bit better what I was thinking

**Comment by Sefa76** [comment]
Yes the normal for-loop integration takes about  ~10 minutes so we want to go through the MCfit ideas to do the integration. I will clean it up a bit and then add it as a switch but honestly this can only be used to compare. To have it clean I will open a new issue for the "real-space" computation
